FROM nginx:stable-alpine

RUN set -xe; \
    mkdir -p /etc/nginx/templates; \
    { \
        echo 'server {'; \
        echo '    location /status {'; \
        echo '        access_log off;'; \
        echo '        stub_status on;'; \
        echo '        allow 127.0.0.1;'; \
        echo '        deny all;'; \
        echo '    }'; \
        echo '}'; \
    } | tee /etc/nginx/templates/default.conf.template; \
