commonLabels: |-
  label.name: {{ .Release.Name }}
  label.chart: {{ .Chart.Name }}

commonAnnotations: |-
  annotation.name: {{ .Release.Name }}
  annotation.chart: {{ .Chart.Name }}

image:
  repository: notexist
  tag: latest
  pullPolicy: IfNotPresent

crons:
  - name: cron1
    schedule: "* * * * *"
    command: echo 'cron 1'
    image:
      repository: php
      tag: 8.0-alpine
      pullPolicy: Always
  - name: cron2
    schedule: "* * * * *"
    command: echo 'cron 2'
    image:
      repository: php
      tag: 8.0-alpine
      pullPolicy: Always

migrations:
  - name: migration1
    command: php -r 'phpinfo();'
    image:
      repository: php
      tag: 8.0-alpine
      pullPolicy: Always

web:
  phpfpm:
    image:
      repository: php
      tag: 8.0-fpm-alpine
      pullPolicy: Always

workers:
  - name: worker1
    replica: 1
    command: while true; do echo 'worker 1'; sleep 10; done
    image:
      repository: php
      tag: 8.0-fpm-alpine
      pullPolicy: Always
  - name: worker2
    replica: 1
    command: while true; do echo 'worker 2'; sleep 10; done
    image:
      repository: php
      tag: 8.0-fpm-alpine
      pullPolicy: Always
